import { StyleSheet } from 'react-native';

import { scale, verticalScale } from 'react-native-size-matters';

import { uiStyle } from '../../../../components/ThemeContext';

const styles = StyleSheet.create({
    page: {
        flex: 1,
    },
    headerShareButton: {
        width: scale(36),
        height: scale(36),
        borderRadius: scale(18),
        alignItems: 'center',
        justifyContent: 'center',
    },
    centeredPage: {
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
        paddingHorizontal: scale(28),
    },
    topicHeader: {
        paddingHorizontal: scale(16),
        paddingVertical: verticalScale(16),
    },
    // 頂部板塊底部分割線：內縮不貼螢幕邊緣
    topicHeaderDivider: {
        height: StyleSheet.hairlineWidth,
        marginHorizontal: scale(16),
    },
    topicTitle: {
        ...uiStyle.defaultText,
        fontSize: scale(22),
        lineHeight: scale(29),
        fontWeight: '700',
    },
    readingControlsDock: {
        position: 'absolute',
        left: 0,
        right: 0,
        bottom: 0,
        zIndex: 20,
    },
    topicActionBar: {
        position: 'absolute',
        left: 0,
        right: 0,
        bottom: 0,
        zIndex: 30,
        flexDirection: 'row',
        alignItems: 'center',
        borderTopWidth: StyleSheet.hairlineWidth,
        paddingHorizontal: scale(10),
        paddingTop: verticalScale(4),
    },
    topicActionCompose: {
        flex: 1,
        minWidth: 0,
        minHeight: verticalScale(30),
        borderRadius: scale(15),
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: scale(10),
        marginRight: scale(4),
    },
    topicActionComposeText: {
        ...uiStyle.defaultText,
        flexShrink: 1,
        fontSize: scale(12),
        marginLeft: scale(5),
    },
    topicActionIcons: {
        flexDirection: 'row',
        alignItems: 'center',
        flexShrink: 0,
    },
    topicActionIconButton: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        paddingHorizontal: scale(5),
        paddingVertical: verticalScale(2),
    },
    topicActionCount: {
        ...uiStyle.defaultText,
        fontSize: scale(11),
        fontWeight: '600',
        marginLeft: scale(3),
    },
    readingControls: {
        borderWidth: StyleSheet.hairlineWidth,
        borderRadius: scale(14),
        marginHorizontal: scale(12),
        marginTop: verticalScale(8),
        paddingHorizontal: scale(12),
        paddingVertical: verticalScale(10),
    },
    progressHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
    },
    progressText: {
        ...uiStyle.defaultText,
        fontSize: scale(11),
        fontWeight: '600',
    },
    progressPercent: {
        ...uiStyle.defaultText,
        fontSize: scale(11),
        fontWeight: '700',
    },
    progressSlider: {
        width: '100%',
        height: verticalScale(28),
        marginTop: verticalScale(2),
    },
    controlRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginTop: verticalScale(4),
    },
    unreadButton: {
        alignSelf: 'center',
        marginTop: verticalScale(2),
        paddingHorizontal: scale(10),
    },
    controlButton: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        borderRadius: scale(7),
        paddingHorizontal: scale(7),
        paddingVertical: verticalScale(5),
    },
    controlButtonText: {
        ...uiStyle.defaultText,
        fontSize: scale(9),
        fontWeight: '600',
        marginLeft: scale(3),
    },
    topicMetaRow: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        alignItems: 'center',
        marginTop: verticalScale(10),
    },
    tagRow: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        alignItems: 'center',
        marginTop: verticalScale(8),
    },
    category: {
        flexDirection: 'row',
        alignItems: 'center',
        borderRadius: scale(7),
        paddingHorizontal: scale(8),
        paddingVertical: verticalScale(4),
        marginRight: scale(6),
        marginBottom: verticalScale(5),
    },
    categoryText: {
        ...uiStyle.defaultText,
        fontSize: scale(11),
        fontWeight: '600',
        marginLeft: scale(4),
    },
    tag: {
        borderRadius: scale(7),
        paddingHorizontal: scale(8),
        paddingVertical: verticalScale(4),
        marginRight: scale(6),
        marginBottom: verticalScale(5),
    },
    tagText: {
        ...uiStyle.defaultText,
        fontSize: scale(11),
        fontWeight: '600',
    },
    lastUpdated: {
        ...uiStyle.defaultText,
        fontSize: scale(11),
        marginTop: verticalScale(7),
    },
    webActionRow: {
        flexDirection: 'row',
        alignItems: 'center',
        flexWrap: 'wrap',
        marginTop: verticalScale(11),
    },
    webOriginalButton: {
        alignSelf: 'flex-start',
        flexDirection: 'row',
        alignItems: 'center',
        borderRadius: scale(9),
        marginRight: scale(6),
        marginBottom: verticalScale(4),
        paddingHorizontal: scale(10),
        paddingVertical: verticalScale(7),
    },
    webOriginalText: {
        ...uiStyle.defaultText,
        fontSize: scale(11),
        fontWeight: '600',
        marginHorizontal: scale(6),
    },
    postCard: {
        paddingHorizontal: scale(16),
        paddingTop: verticalScale(16),
        overflow: 'hidden',
    },
    // 1 樓底部內縮分割線（相對貼文內容區，不貼螢幕邊）
    firstPostDivider: {
        height: StyleSheet.hairlineWidth,
        marginTop: verticalScale(8),
    },
    postStateCard: {
        borderWidth: StyleSheet.hairlineWidth,
        borderRadius: scale(10),
        flexDirection: 'row',
        alignItems: 'center',
        marginHorizontal: scale(12),
        marginVertical: verticalScale(4),
        paddingHorizontal: scale(10),
        paddingVertical: verticalScale(7),
    },
    postStateText: {
        ...uiStyle.defaultText,
        flex: 1,
        fontSize: scale(12),
        marginLeft: scale(7),
    },
    postStateNumber: {
        ...uiStyle.defaultText,
        fontSize: scale(10),
        marginLeft: scale(7),
    },
    noticeContent: {
        flex: 1,
        marginLeft: scale(7),
    },
    noticeTitle: {
        ...uiStyle.defaultText,
        fontSize: scale(11),
        fontWeight: '700',
        marginBottom: verticalScale(3),
    },
    postHeader: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    // 回覆帖：頭像左側，ID／正文／操作列右側對齊
    replyLayout: {
        flexDirection: 'row',
        alignItems: 'flex-start',
    },
    replyAvatarPressable: {
        flexShrink: 0,
        marginTop: verticalScale(1),
    },
    replyMain: {
        flex: 1,
        marginLeft: scale(8),
        minWidth: 0,
    },
    replyHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: verticalScale(2),
    },
    replyAuthorPressable: {
        flex: 1,
        minWidth: 0,
    },
    replyAuthorName: {
        fontWeight: '400',
    },
    replyBody: {
        marginTop: 0,
    },
    firstPostCard: {
        paddingTop: verticalScale(12),
        paddingBottom: verticalScale(10),
    },
    firstPostHeader: {
        marginBottom: 0,
    },
    firstPostTitle: {
        ...uiStyle.defaultText,
        fontSize: scale(16),
        lineHeight: scale(21),
        fontWeight: '700',
        marginTop: verticalScale(6),
    },
    firstPostBody: {
        marginTop: verticalScale(4),
    },
    firstPostPlainTagRow: {
        marginTop: verticalScale(4),
    },
    firstPostMetaRow: {
        marginTop: verticalScale(6),
        marginBottom: 0,
    },
    plainTagRow: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        alignItems: 'center',
        marginTop: verticalScale(8),
    },
    plainTag: {
        flexDirection: 'row',
        alignItems: 'center',
        marginRight: scale(10),
        marginBottom: verticalScale(2),
    },
    plainTagText: {
        ...uiStyle.defaultText,
        fontSize: scale(12),
        fontWeight: '500',
        marginLeft: scale(3),
    },
    authorLink: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
        minWidth: 0,
    },
    headerMeta: {
        flexDirection: 'row',
        alignItems: 'center',
        flexShrink: 0,
        marginLeft: scale(8),
    },
    pressedLink: {
        opacity: 0.7,
    },
    avatar: {
        width: scale(30),
        height: scale(30),
        borderRadius: scale(15),
    },
    authorArea: {
        flex: 1,
        marginLeft: scale(8),
        minWidth: 0,
    },
    authorNameRow: {
        flexDirection: 'row',
        alignItems: 'center',
        minWidth: 0,
    },
    authorName: {
        ...uiStyle.defaultText,
        flexShrink: 1,
        fontSize: scale(12),
        lineHeight: scale(16),
        fontWeight: '500',
    },
    userTitle: {
        ...uiStyle.defaultText,
        flexShrink: 1,
        fontSize: scale(10),
        lineHeight: scale(14),
        marginLeft: scale(6),
    },
    staffBadge: {
        ...uiStyle.defaultText,
        fontSize: scale(9),
        fontWeight: '700',
        borderRadius: scale(5),
        marginLeft: scale(5),
        paddingHorizontal: scale(5),
        paddingVertical: verticalScale(1),
        overflow: 'hidden',
    },
    postTime: {
        ...uiStyle.defaultText,
        flexShrink: 1,
        fontSize: scale(10),
        marginRight: scale(8),
    },
    postMetaRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginTop: verticalScale(1),
        marginBottom: verticalScale(1),
    },
    postMetaActions: {
        flexDirection: 'row',
        alignItems: 'center',
        flexShrink: 0,
        marginLeft: scale(8),
        columnGap: scale(2),
    },
    postMetaIconMenu: {
        width: scale(26),
        height: scale(26),
        flexShrink: 0,
    },
    postMetaIconButton: {
        width: scale(26),
        height: scale(26),
        alignItems: 'center',
        justifyContent: 'center',
    },
    postMetaStats: {
        flexDirection: 'row',
        alignItems: 'center',
        flexShrink: 0,
    },
    postMetaComment: {
        marginRight: 0,
        marginLeft: scale(8),
    },
    postNumber: {
        ...uiStyle.defaultText,
        fontSize: scale(11),
        fontWeight: '600',
        marginLeft: scale(6),
    },
    replyBadge: {
        flexDirection: 'row',
        alignItems: 'center',
        borderRadius: scale(6),
        paddingHorizontal: scale(6),
        paddingVertical: verticalScale(3),
    },
    replyText: {
        ...uiStyle.defaultText,
        fontSize: scale(9),
        fontWeight: '600',
        marginLeft: scale(3),
    },
    // 展開回覆：左右分割線與日期列同寬（在 replyMain / 1 樓內容區內）
    nestedRepliesButton: {
        alignSelf: 'stretch',
        flexDirection: 'row',
        alignItems: 'center',
        minHeight: verticalScale(22),
        marginTop: verticalScale(2),
        marginBottom: verticalScale(4),
    },
    nestedRepliesLine: {
        flex: 1,
        height: StyleSheet.hairlineWidth,
    },
    nestedRepliesText: {
        ...uiStyle.defaultText,
        fontSize: scale(11),
        fontWeight: '600',
        marginHorizontal: scale(8),
    },
    postBody: {
        marginTop: verticalScale(8),
    },
    inlineEmoji: {
        width: scale(18),
        height: scale(18),
    },
    iframeContainer: {
        overflow: 'hidden',
        borderRadius: scale(10),
        marginVertical: verticalScale(8),
    },
    interactiveFallback: {
        alignSelf: 'flex-start',
        flexDirection: 'row',
        alignItems: 'center',
        borderRadius: scale(8),
        marginBottom: verticalScale(8),
        paddingHorizontal: scale(9),
        paddingVertical: verticalScale(7),
    },
    interactiveFallbackText: {
        ...uiStyle.defaultText,
        fontSize: scale(11),
        fontWeight: '600',
        marginLeft: scale(5),
    },
    eventCard: {
        flexDirection: 'row',
        alignItems: 'flex-start',
        borderWidth: StyleSheet.hairlineWidth,
        borderRadius: scale(12),
        marginTop: verticalScale(8),
        marginBottom: verticalScale(4),
        paddingHorizontal: scale(10),
        paddingVertical: verticalScale(10),
    },
    eventDateBlock: {
        width: scale(46),
        borderRadius: scale(10),
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: verticalScale(8),
        marginRight: scale(10),
    },
    eventDateMonth: {
        ...uiStyle.defaultText,
        fontSize: scale(10),
        fontWeight: '600',
    },
    eventDateDay: {
        ...uiStyle.defaultText,
        fontSize: scale(20),
        lineHeight: scale(24),
        fontWeight: '700',
        marginTop: verticalScale(2),
    },
    eventBody: {
        flex: 1,
        minWidth: 0,
    },
    eventTitleRow: {
        flexDirection: 'row',
        alignItems: 'flex-start',
        flexWrap: 'wrap',
    },
    eventTitle: {
        ...uiStyle.defaultText,
        flexShrink: 1,
        fontSize: scale(15),
        lineHeight: scale(21),
        fontWeight: '700',
        marginRight: scale(6),
    },
    eventStatus: {
        ...uiStyle.defaultText,
        fontSize: scale(12),
        lineHeight: scale(21),
        fontWeight: '700',
    },
    eventMetaRow: {
        flexDirection: 'row',
        alignItems: 'flex-start',
        marginTop: verticalScale(4),
        gap: scale(4),
    },
    eventMetaText: {
        ...uiStyle.defaultText,
        flex: 1,
        fontSize: scale(12),
        lineHeight: scale(17),
    },
    eventGoingText: {
        ...uiStyle.defaultText,
        fontSize: scale(12),
        lineHeight: scale(17),
        marginTop: verticalScale(4),
    },
    eventCreatorText: {
        ...uiStyle.defaultText,
        fontSize: scale(12),
        lineHeight: scale(17),
        marginTop: verticalScale(2),
    },
    postFooter: {
        minHeight: verticalScale(38),
        borderTopWidth: StyleSheet.hairlineWidth,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginTop: verticalScale(5),
    },
    postActionRow: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingBottom: verticalScale(10),
    },
    composerActionRow: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingBottom: verticalScale(6),
    },
    composerMenuView: {
        flex: 1,
    },
    reactionMenuView: {
        flex: 1,
        marginRight: scale(6),
    },
    reactionMenuButton: {
        marginRight: 0,
    },
    disabledAction: {
        opacity: 0.45,
    },
    postActionButton: {
        minWidth: scale(72),
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        borderRadius: scale(8),
        marginRight: scale(6),
        paddingHorizontal: scale(7),
        paddingVertical: verticalScale(7),
    },
    postActionText: {
        ...uiStyle.defaultText,
        flexShrink: 1,
        fontSize: scale(10),
        fontWeight: '600',
        marginLeft: scale(4),
    },
    postIconButton: {
        width: scale(34),
        height: verticalScale(30),
        borderRadius: scale(8),
        alignItems: 'center',
        justifyContent: 'center',
        marginLeft: scale(4),
    },
    footerMeta: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    reactionSummary: {
        flexDirection: 'row',
        alignItems: 'center',
        flexWrap: 'wrap',
    },
    reactionSummaryItem: {
        flexDirection: 'row',
        alignItems: 'center',
        marginLeft: scale(8),
        paddingVertical: verticalScale(2),
    },
    reactionSummaryText: {
        ...uiStyle.defaultText,
        fontSize: scale(10),
        marginLeft: scale(2),
    },
    metaItem: {
        flexDirection: 'row',
        alignItems: 'center',
        marginRight: scale(12),
    },
    metaText: {
        ...uiStyle.defaultText,
        fontSize: scale(10),
        marginLeft: scale(3),
    },
    skeletonBlock: {
        borderRadius: scale(4),
    },
    skeletonContent: {
        flex: 1,
        overflow: 'hidden',
    },
    skeletonTopicTitle: {
        width: '78%',
        height: scale(22),
    },
    skeletonTopicTitleShort: {
        width: '48%',
        height: scale(22),
        marginTop: verticalScale(7),
    },
    skeletonCategory: {
        width: '26%',
        height: verticalScale(27),
        borderRadius: scale(7),
        marginTop: verticalScale(12),
    },
    skeletonTopicMeta: {
        flexDirection: 'row',
        alignItems: 'center',
        marginTop: verticalScale(13),
    },
    skeletonTopicMetaItem: {
        width: scale(52),
        height: verticalScale(10),
        marginRight: scale(12),
    },
    skeletonLastUpdated: {
        width: '48%',
        height: verticalScale(10),
        marginTop: verticalScale(10),
    },
    skeletonWebActions: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        marginTop: verticalScale(12),
    },
    skeletonWebAction: {
        width: '24%',
        height: verticalScale(34),
        borderRadius: scale(9),
        marginRight: scale(6),
        marginBottom: verticalScale(6),
    },
    skeletonWebActionWide: {
        width: '38%',
        height: verticalScale(34),
        borderRadius: scale(9),
        marginRight: scale(6),
        marginBottom: verticalScale(6),
    },
    skeletonAvatar: {
        width: scale(30),
        height: scale(30),
        borderRadius: scale(15),
    },
    skeletonAuthorArea: {
        flex: 1,
        marginLeft: scale(8),
        justifyContent: 'center',
    },
    skeletonAuthorName: {
        width: '44%',
        height: verticalScale(12),
    },
    skeletonPostTime: {
        width: '38%',
        height: verticalScale(9),
        flexShrink: 1,
        marginRight: scale(8),
    },
    skeletonPostNumber: {
        width: scale(20),
        height: verticalScale(10),
        marginLeft: scale(8),
    },
    skeletonPostBody: {
        marginTop: verticalScale(10),
    },
    skeletonBodyLine: {
        width: '94%',
        height: verticalScale(12),
    },
    skeletonBodyLineMedium: {
        width: '76%',
        height: verticalScale(12),
        marginTop: verticalScale(7),
    },
    skeletonBodyLineShort: {
        width: '52%',
        height: verticalScale(12),
        marginTop: verticalScale(7),
    },
    skeletonFooterMeta: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    skeletonMetaItem: {
        width: scale(34),
        height: verticalScale(10),
        marginLeft: scale(8),
    },
    skeletonPostAction: {
        flex: 1,
        height: verticalScale(32),
        borderRadius: scale(8),
    },
    skeletonPostActionWide: {
        flex: 1.6,
        height: verticalScale(32),
        borderRadius: scale(8),
        marginRight: scale(6),
    },
    skeletonProgressLabel: {
        width: '28%',
        height: verticalScale(11),
    },
    skeletonProgressPercent: {
        width: '10%',
        height: verticalScale(11),
    },
    skeletonProgressTrack: {
        height: verticalScale(8),
        borderRadius: scale(999),
        marginTop: verticalScale(12),
        overflow: 'hidden',
    },
    skeletonProgressFill: {
        width: '34%',
        height: '100%',
        borderRadius: scale(999),
    },
    skeletonControlButton: {
        width: '29%',
        height: verticalScale(30),
        borderRadius: scale(8),
    },
    unreadDivider: {
        flexDirection: 'row',
        alignItems: 'center',
        marginHorizontal: scale(16),
        marginVertical: verticalScale(7),
    },
    unreadDividerLine: {
        flex: 1,
        height: StyleSheet.hairlineWidth,
    },
    unreadDividerText: {
        ...uiStyle.defaultText,
        fontSize: scale(10),
        fontWeight: '700',
        marginHorizontal: scale(8),
    },
    edgeLoader: {
        marginVertical: verticalScale(12),
    },
    topicReplyButton: {
        minHeight: verticalScale(42),
        borderRadius: scale(11),
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        marginHorizontal: scale(12),
        marginTop: verticalScale(10),
        paddingHorizontal: scale(16),
    },
    topicReplyButtonText: {
        ...uiStyle.defaultText,
        fontSize: scale(13),
        fontWeight: '700',
        marginLeft: scale(6),
    },
    relatedTopics: {
        borderWidth: StyleSheet.hairlineWidth,
        borderRadius: scale(14),
        marginHorizontal: scale(12),
        marginTop: verticalScale(10),
        marginBottom: verticalScale(10),
        overflow: 'hidden',
    },
    relatedTitle: {
        ...uiStyle.defaultText,
        fontSize: scale(15),
        fontWeight: '700',
        paddingHorizontal: scale(12),
        paddingVertical: verticalScale(11),
    },
    relatedTopic: {
        minHeight: verticalScale(42),
        borderTopWidth: StyleSheet.hairlineWidth,
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: scale(12),
        paddingVertical: verticalScale(8),
    },
    relatedTopicTitle: {
        ...uiStyle.defaultText,
        flex: 1,
        fontSize: scale(12),
        lineHeight: scale(17),
    },
    listFooter: {
        height: verticalScale(12),
    },
    newRepliesButton: {
        position: 'absolute',
        left: scale(28),
        right: scale(28),
        minHeight: verticalScale(42),
        borderRadius: scale(21),
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        paddingHorizontal: scale(16),
        zIndex: 21,
    },
    newRepliesButtonText: {
        ...uiStyle.defaultText,
        fontSize: scale(13),
        fontWeight: '700',
        marginLeft: scale(6),
    },
    modalPage: {
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
        paddingHorizontal: scale(28),
    },
    modalBackdrop: {
        opacity: 0.55,
    },
    jumpDialog: {
        width: '100%',
        borderRadius: scale(16),
        paddingHorizontal: scale(18),
        paddingVertical: verticalScale(16),
    },
    jumpDialogTitle: {
        ...uiStyle.defaultText,
        fontSize: scale(17),
        fontWeight: '700',
    },
    jumpDialogHint: {
        ...uiStyle.defaultText,
        fontSize: scale(11),
        marginTop: verticalScale(4),
    },
    jumpInput: {
        ...uiStyle.defaultText,
        borderWidth: StyleSheet.hairlineWidth,
        borderRadius: scale(9),
        fontSize: scale(16),
        marginTop: verticalScale(12),
        paddingHorizontal: scale(11),
        paddingVertical: verticalScale(8),
    },
    jumpDialogActions: {
        flexDirection: 'row',
        justifyContent: 'flex-end',
        marginTop: verticalScale(12),
    },
    jumpDialogButton: {
        minWidth: scale(72),
        alignItems: 'center',
        borderRadius: scale(8),
        marginLeft: scale(8),
        paddingHorizontal: scale(12),
        paddingVertical: verticalScale(8),
    },
    jumpDialogButtonText: {
        ...uiStyle.defaultText,
        fontSize: scale(12),
        fontWeight: '700',
    },
    actionDialog: {
        width: '100%',
        maxHeight: '88%',
        borderRadius: scale(16),
        paddingHorizontal: scale(18),
        paddingVertical: verticalScale(16),
    },
    actionDialogTitle: {
        ...uiStyle.defaultText,
        fontSize: scale(17),
        fontWeight: '700',
        marginBottom: verticalScale(10),
    },
    actionDialogLabel: {
        ...uiStyle.defaultText,
        fontSize: scale(11),
        fontWeight: '600',
        marginBottom: verticalScale(5),
    },
    bookmarkNameInput: {
        ...uiStyle.defaultText,
        borderWidth: StyleSheet.hairlineWidth,
        borderRadius: scale(9),
        fontSize: scale(13),
        marginBottom: verticalScale(12),
        paddingHorizontal: scale(11),
        paddingVertical: verticalScale(8),
    },
    bookmarkReminderRow: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    reminderButton: {
        minHeight: verticalScale(34),
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        borderRadius: scale(8),
        paddingHorizontal: scale(10),
    },
    reminderDateButton: {
        flex: 1,
        marginLeft: scale(7),
    },
    reminderButtonText: {
        ...uiStyle.defaultText,
        flexShrink: 1,
        fontSize: scale(11),
        fontWeight: '600',
        marginLeft: scale(4),
    },
    actionDialogActions: {
        flexDirection: 'row',
        justifyContent: 'flex-end',
        flexWrap: 'wrap',
        marginTop: verticalScale(16),
    },
    actionDialogButton: {
        minWidth: scale(70),
        alignItems: 'center',
        borderRadius: scale(8),
        marginLeft: scale(7),
        marginTop: verticalScale(5),
        paddingHorizontal: scale(11),
        paddingVertical: verticalScale(8),
    },
    actionDialogButtonText: {
        ...uiStyle.defaultText,
        fontSize: scale(11),
        fontWeight: '700',
    },
    reactionGlyph: {
        textAlign: 'center',
    },
    reactionFallbackText: {
        ...uiStyle.defaultText,
        fontWeight: '600',
        textAlign: 'center',
    },
    notificationOption: {
        minHeight: verticalScale(54),
        borderTopWidth: StyleSheet.hairlineWidth,
        flexDirection: 'row',
        alignItems: 'center',
        borderRadius: scale(8),
        paddingHorizontal: scale(10),
        paddingVertical: verticalScale(7),
    },
    notificationContent: {
        flex: 1,
        marginHorizontal: scale(9),
    },
    notificationLabel: {
        ...uiStyle.defaultText,
        fontSize: scale(12),
        fontWeight: '700',
    },
    notificationDescription: {
        ...uiStyle.defaultText,
        fontSize: scale(10),
        lineHeight: scale(14),
        marginTop: verticalScale(2),
    },
    errorIcon: {
        width: scale(64),
        height: scale(64),
        borderRadius: scale(32),
        alignItems: 'center',
        justifyContent: 'center',
        marginBottom: verticalScale(14),
    },
    errorTitle: {
        ...uiStyle.defaultText,
        fontSize: scale(18),
        fontWeight: '700',
        textAlign: 'center',
    },
    errorDescription: {
        ...uiStyle.defaultText,
        fontSize: scale(13),
        lineHeight: scale(19),
        textAlign: 'center',
        marginTop: verticalScale(6),
    },
    primaryButton: {
        minWidth: scale(150),
        alignItems: 'center',
        borderRadius: scale(11),
        marginTop: verticalScale(18),
        paddingHorizontal: scale(18),
        paddingVertical: verticalScale(10),
    },
    primaryButtonText: {
        ...uiStyle.defaultText,
        fontSize: scale(14),
        fontWeight: '700',
    },
    secondaryButton: {
        minWidth: scale(150),
        alignItems: 'center',
        borderRadius: scale(11),
        marginTop: verticalScale(8),
        paddingHorizontal: scale(18),
        paddingVertical: verticalScale(10),
    },
    secondaryButtonText: {
        ...uiStyle.defaultText,
        fontSize: scale(13),
        fontWeight: '600',
    },
});

export default styles;
