ENV['RCT_NEW_ARCH_ENABLED'] = '0'

# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

# 2. Firebase 需要靜態庫 (Static Frameworks)
# RN 0.76+ 對 use_frameworks! :linkage => :static 的支持已大幅改善
use_frameworks! :linkage => :static

# Firebase 靜態設置
$RNFirebaseAsStaticFramework = true

# 修復iOS無法統計設型號問題
$RNFirebaseAnalyticsEnableAdSupport = true

target 'UMALL' do
  config = use_native_modules!

  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    # 嘗試使用bridge模式，為了Firebase
    :hermes_enabled => flags[:hermes_enabled],
    :fabric_enabled => flags[:fabric_enabled],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )

  end
end
