import { Notifications } from 'react-native-notifications';

// 需要到index或App.js中初始化
// Notifications.events().registerNotificationReceivedForeground((notification, completion) => {
//     console.log("Notification Received - Foreground", notification.payload);

//     // Calling completion on iOS with `alert: true` will present the native iOS inApp notification.
//     completion({ alert: true, sound: true, badge: false });
// });

// Notifications.events().registerNotificationOpened((notification, completion, action) => {
//     console.log("Notification opened by device user", notification.payload);
//     console.log(`Notification opened with an action identifier: ${action.identifier} and response text: ${action.text}`);
//     completion();
// });


// 需要的地方調用本地通知
// Notifications.postLocalNotification({
//     title: "Local notification",
//     body: "This notification was generated by the app!",
// });